feat: update custom dictionary and add loggi functions
 - **Custom Dictionary**:
   - Added new entries: , .

 - **Dot-Files**:
   - Introduced ^Cthread '<unnamed>' panicked at src/validators/mod.rs:375:23:
Error building schema validator:
  KeyboardInterrupt:
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/opt/loggi/payout/manage.py", line 4, in <module>
    from core.db.django import initialize_orm
  File "/opt/loggi/payout/src/core/db/django.py", line 7, in <module>
    from core.settings import get_settings
  File "/opt/loggi/payout/src/core/settings.py", line 3, in <module>
    from kafkax import SASLMechanism, SecurityProtocol
  File "/usr/local/lib/python3.11/site-packages/kafkax/__init__.py", line 3, in <module>
    from .conf import (
  File "/usr/local/lib/python3.11/site-packages/kafkax/conf.py", line 23, in <module>
    class RetryStrategyConfiguration(BaseModel):
  File "/usr/local/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 183, in __new__
    complete_model_class(
  File "/usr/local/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 527, in complete_model_class
    schema = gen_schema.clean_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 430, in clean_schema
    schema = validate_core_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 570, in validate_core_schema
    return _validate_core_schema(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Error building schema validator:
  KeyboardInterrupt:  function to execute a shell in the
 namespace using kubectl controls the Kubernetes cluster manager.

 Find more information at: https://kubernetes.io/docs/reference/kubectl/

Basic Commands (Beginner):
  create          Create a resource from a file or from stdin
  expose          Take a replication controller, service, deployment or pod and expose it as a new Kubernetes service
  run             Run a particular image on the cluster
  set             Set specific features on objects

Basic Commands (Intermediate):
  explain         Get documentation for a resource
  get             Display one or many resources
  edit            Edit a resource on the server
  delete          Delete resources by file names, stdin, resources and names, or by resources and label selector

Deploy Commands:
  rollout         Manage the rollout of a resource
  scale           Set a new size for a deployment, replica set, or replication controller
  autoscale       Auto-scale a deployment, replica set, stateful set, or replication controller

Cluster Management Commands:
  certificate     Modify certificate resources
  cluster-info    Display cluster information
  top             Display resource (CPU/memory) usage
  cordon          Mark node as unschedulable
  uncordon        Mark node as schedulable
  drain           Drain node in preparation for maintenance
  taint           Update the taints on one or more nodes

Troubleshooting and Debugging Commands:
  describe        Show details of a specific resource or group of resources
  logs            Print the logs for a container in a pod
  attach          Attach to a running container
  exec            Execute a command in a container
  port-forward    Forward one or more local ports to a pod
  proxy           Run a proxy to the Kubernetes API server
  cp              Copy files and directories to and from containers
  auth            Inspect authorization
  debug           Create debugging sessions for troubleshooting workloads and nodes
  events          List events

Advanced Commands:
  diff            Diff the live version against a would-be applied version
  apply           Apply a configuration to a resource by file name or stdin
  patch           Update fields of a resource
  replace         Replace a resource by file name or stdin
  wait            Experimental: Wait for a specific condition on one or many resources
  kustomize       Build a kustomization target from a directory or URL

Settings Commands:
  label           Update the labels on a resource
  annotate        Update the annotations on a resource
  completion      Output shell completion code for the specified shell (bash, zsh, fish, or powershell)

Subcommands provided by plugins:

Other Commands:
  api-resources   Print the supported API resources on the server
  api-versions    Print the supported API versions on the server, in the form of "group/version"
  config          Modify kubeconfig files
  plugin          Provides utilities for interacting with plugins
  version         Print the client and server version information

Usage:
  kubectl [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands)..
   - Added a usage: loggi <command> <options>

Loggi client to control local development environment.

The following commands are available:

  android         build an Android repository
  autopep8        run autopep8 formating for loggi-web in files failing pep8 test
  aws-shell       starts aws-shell. You have to run configure
  az              run azure cli
  bash            start bash session in app container
  beat            start celery beat (scheduler)
  check           check if loggi-web container is alive
  clean-manifest  clean static manifest cache
  clean-pyc       remove *.pyc files
  db-cli          starts a pg-cli, gets env as param (default: dev)
  db-dump         creates a dump of the database
  db-load-dump    loads a database dump
  down            stop and remove all containers
  fix-keys        fix ssh keys permissions
  front           build a frontend repository
  goaccess        start goaccess log analyzer
  goprod          start shell_plus in production
  gosandbox       start shell_plus in sandbox
  gostaging       start shell_plus in staging
  gostaging-az    start shell_plus in staging azure
  gowop           start shell_plus in wop
  graphiql        copy static assets to proper folder in app
  help            help
  html-to-pdf     starts html-to-pdf container
  ipython         start ipython repl in loggi-web local env
  kafka           run kafka commands
  kubectl         run kubectl commands
  kubectl-exec    run kubectl commands with container interactive
  kubectl-proxy   open the kubectl dashboard
  lint            run linters for loggi-web (code style)
  native          build or deploy a react native bundle
  nfe-roller      starts nfe-roller container
  nono            dubas nono
  notebook        starts ipython notebook server
  pginsight       run pginsight, gets env and cmd as param
  pip             runs pip in app container
  pip-install     runs pip-install in app container
  pm              run manage.py command in app container
  psql            run psql, gets env as param (default: dev)
  ptw             run tests for loggi-web as a local continuous test runner
  restart         restart loggi web container
  scp             scp to machine, gets env, node and file as args
  setup-dev-db[DEPRECATED]    setup development database
  shell_plus      start your default repl in loggi-web local env
  shellp          connect to shell_plus in production disposable
  shells          connect to shell_plus in staging disposable
  ssh             ssh to machine, gets env and node as args
  sshci           ssh to ci, gets node as arg
  sshp            ssh to production, gets node as arg
  sshqa           ssh to qa, gets node as arg
  sshs            ssh to staging, gets node as arg
  sshv            ssh to volumetry, gets node as arg
  submodules      run update git submodules recursively
  terraform       run terraform
  test            run tests for loggi-web
  test-report     run tests for loggi-web and generate html report of status and code coverage
  test-routing    run tests for routing
  up              run (recreate) all containers
  validate-schema validate UI GraphQL schema

  Additionally, you can use this command as you would use docker,
  for example, you can run: loggi ps function to handle different cases, specifically for
 , and fallback to the system's usage: loggi <command> <options>

Loggi client to control local development environment.

The following commands are available:

  android         build an Android repository
  autopep8        run autopep8 formating for loggi-web in files failing pep8 test
  aws-shell       starts aws-shell. You have to run configure
  az              run azure cli
  bash            start bash session in app container
  beat            start celery beat (scheduler)
  check           check if loggi-web container is alive
  clean-manifest  clean static manifest cache
  clean-pyc       remove *.pyc files
  db-cli          starts a pg-cli, gets env as param (default: dev)
  db-dump         creates a dump of the database
  db-load-dump    loads a database dump
  down            stop and remove all containers
  fix-keys        fix ssh keys permissions
  front           build a frontend repository
  goaccess        start goaccess log analyzer
  goprod          start shell_plus in production
  gosandbox       start shell_plus in sandbox
  gostaging       start shell_plus in staging
  gostaging-az    start shell_plus in staging azure
  gowop           start shell_plus in wop
  graphiql        copy static assets to proper folder in app
  help            help
  html-to-pdf     starts html-to-pdf container
  ipython         start ipython repl in loggi-web local env
  kafka           run kafka commands
  kubectl         run kubectl commands
  kubectl-exec    run kubectl commands with container interactive
  kubectl-proxy   open the kubectl dashboard
  lint            run linters for loggi-web (code style)
  native          build or deploy a react native bundle
  nfe-roller      starts nfe-roller container
  nono            dubas nono
  notebook        starts ipython notebook server
  pginsight       run pginsight, gets env and cmd as param
  pip             runs pip in app container
  pip-install     runs pip-install in app container
  pm              run manage.py command in app container
  psql            run psql, gets env as param (default: dev)
  ptw             run tests for loggi-web as a local continuous test runner
  restart         restart loggi web container
  scp             scp to machine, gets env, node and file as args
  setup-dev-db[DEPRECATED]    setup development database
  shell_plus      start your default repl in loggi-web local env
  shellp          connect to shell_plus in production disposable
  shells          connect to shell_plus in staging disposable
  ssh             ssh to machine, gets env and node as args
  sshci           ssh to ci, gets node as arg
  sshp            ssh to production, gets node as arg
  sshqa           ssh to qa, gets node as arg
  sshs            ssh to staging, gets node as arg
  sshv            ssh to volumetry, gets node as arg
  submodules      run update git submodules recursively
  terraform       run terraform
  test            run tests for loggi-web
  test-report     run tests for loggi-web and generate html report of status and code coverage
  test-routing    run tests for routing
  up              run (recreate) all containers
  validate-schema validate UI GraphQL schema

  Additionally, you can use this command as you would use docker,
  for example, you can run: loggi ps command.

This commit enhances the custom dictionary with new terms and introduces new
functions in the dot-files to streamline operations related to the loggi
application.